server:
  port: 8004
spring:
  application:
    name: ms-bike
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: "jdbc:h2:mem:bike_db;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop

